[profile.default]
src = "src"
out = "out"
libs = ["lib", 'node_modules']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
MAINNET_RPC_URL = "${MAINNET_RPC_URL}" 